# Generated by Django 6.0.1 on 2026-01-10 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône Lucide (ex: video, mic)", max_length=100, verbose_name='Icône (Lucide)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie de production',
                'verbose_name_plural': 'Catégories de production',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Lien vidéo/audio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='production/', verbose_name='Image de couverture')),
                ('published_at', models.DateTimeField(verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productioncategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
                'ordering': ['-published_at'],
            },
        ),
    ]
