# Generated by Django 6.0.1 on 2026-01-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre (FR)')),
                ('content', models.TextField(help_text='Contenu en format MDX', verbose_name='Contenu (FR)')),
                ('excerpt', models.TextField(blank=True, verbose_name='Extrait (FR)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Titre (EN)')),
                ('content_en', models.TextField(help_text='Contenu en format MDX', verbose_name='Contenu (EN)')),
                ('excerpt_en', models.TextField(blank=True, verbose_name='Extrait (EN)')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Image à la une')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Article de blog',
                'verbose_name_plural': 'Articles de blog',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
