# Generated by Django 6.0.1 on 2026-01-10 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='blog/media/', verbose_name='Fichier')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=10, verbose_name='Type de média')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description (Alt text)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='blog.blogpost', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Média de blog',
                'verbose_name_plural': 'Médias de blog',
            },
        ),
    ]
