# Generated by Django 6.0.1 on 2026-01-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('value', models.SlugField(max_length=200, unique=True, verbose_name='Valeur (identifiant)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Sujet de contact',
                'verbose_name_plural': 'Sujets de contact',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='request_type',
            field=models.CharField(max_length=200, verbose_name='Type de demande'),
        ),
    ]
