# Generated by Django 6.0.1 on 2026-01-10 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('content', models.TextField(blank=True, help_text='Contenu au format MDX ou HTML', verbose_name='Contenu principal')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Image à la une')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du bloc')),
                ('content', models.TextField(help_text='Contenu au format texte ou MDX', verbose_name='Contenu du bloc')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône Lucide (ex: briefcase, graduation-cap)", max_length=100, verbose_name='Icône (Lucide)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.page', verbose_name='Page parente')),
            ],
            options={
                'verbose_name': 'Bloc de contenu',
                'verbose_name_plural': 'Blocs de contenu',
                'ordering': ['order'],
            },
        ),
    ]
