services:
  monsieurdanko:
    image: ghcr.io/aureldsk02/monsieurdanko:latest
    container_name: monsieurdanko
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env
    expose: 
      - 3000

    volumes:
      # Persist uploaded images across redeployments
      - uploads_data:/app/public/uploads

    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10" # 1GB max

    labels:
      # Enable Traefik and specify instance
      - traefik.enable=true
      - traefik.instance=main

      # Router: domain, entrypoints, TLS
      # HTTP
      - traefik.http.routers.monsieurdanko_http.rule=Host(`monsieurdanko.com`) && PathPrefix(`/`)
      - traefik.http.routers.monsieurdanko_http.entrypoints=web
      - traefik.http.routers.monsieurdanko_http.middlewares=https-redirect@file,security-headers@file

      # HTTPS
      - traefik.http.routers.monsieurdanko.rule=Host(`monsieurdanko.com`) && PathPrefix(`/`)
      - traefik.http.routers.monsieurdanko.middlewares=security-headers@file
      - traefik.http.routers.monsieurdanko.entrypoints=websecure
      - traefik.http.routers.monsieurdanko.tls=true
      - traefik.http.routers.monsieurdanko.tls.certresolver=main_resolver

      # Service internal port
      - traefik.http.services.monsieurdanko.loadbalancer.server.port=3000


    networks:
      - base-traefik

volumes:
  uploads_data:
    driver: local

networks:
  base-traefik:
    external: true
