# Generated by Django 6.0.1 on 2026-01-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('category', models.CharField(help_text='ex: Employabilité, Développement social', max_length=100, verbose_name='Catégorie')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône Lucide (ex: target, users)", max_length=100, verbose_name='Icône (Lucide)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('link', models.URLField(blank=True, null=True, verbose_name='Lien externe')),
            ],
            options={
                'verbose_name': 'Initiative',
                'verbose_name_plural': 'Initiatives',
                'ordering': ['order'],
            },
        ),
    ]
